#!/bin/sh

# Set the screen resolution and wallpaper.
refreshresolution &

# Set the input volume.
amixer set Capture 40% &

# Enable transparency and fix screen tearing.
(sleep 0.5 && xcompmgr) &

# Setup notifications.
dunst &

# Setup the status bar.
slstatus &
